server:
  port: 80

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/flow?serverTimezone=UTC
#    username: root
#    password: Dongcci92!!
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        default_batch_fetch_size: 1000
#      ddl-auto: create
#      database-platform: org.hibernate.dialect.MySQL8Dialect
#  thymeleaf:
#    cache: false
#  servlet:
#    multipart:
#      maxFileSize: 20MB
#      maxRequestSize: 100MB
#
#itemImgLocation: /Users/proxy/items/item/
#uploadPath: file:/Users/proxy/items/